server:
  ssl:
    key-store: "${SERVER_SSL_KEY_STORE}"
    key-store-type: PKCS12
    key-store-password: "${SERVER_SSL_KEY_STORE_PASSWORD}"
  port: 443

spring:
  jwt:
    secret-key: "${JWT_SECRET_KEY}"
    redirect: "https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login?name=%s&user_uuid=%s"
    access-token:
      expiration-time: 3600000
    refresh-token:
      expiration-time: 604800000
    security:
    oauth2:
      client:
        registration:

          google:
            client-id: 68070665235-qvdshelcl2eja5amt37urbhqgpuuv4ve.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/google

          kakao:
            client-id: 6b1d134980644fe3a21d1a0f09b52c4d
            client-secret: 6CE5ZNnGwrIfqkAjBENpiFIik67OsSdE
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: hbhB10Tk7nEfIWzdZDnW
            client-secret: TR7P0nBX0D
            scope:
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/naver

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

cloud:
  aws:
    s3:
      bucket: yoons-s3
    region:
      static: ap-northeast-2
    credentials:
      accessKey: "${AWS_ACCESS_KEY_ID}"
      secretKey: "${AWS_SECRET_ACCESS_KEY}"
