server:
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-type: PKCS12
    key-store-password: asdttycc
  port: 443

spring:
  jwt:
    secret-key: "hadgfsfsfsfsssfsfssfsfsfsffasadad1234567890"  # JWT 비밀 키 (256비트 이상)
    redirect: "https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login?name=%s&user_uuid=%s"  # 로그인 후 리디렉션 URL (사용자 uuid 포함)
    access-token:
      expiration-time: 3600000  # 액세스 토큰 만료 시간 (밀리초 단위, 1시간)
    refresh-token:
      expiration-time: 604800000  # 리프레시 토큰 만료 시간 (밀리초 단위, 7일)

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 68070665235-qvdshelcl2eja5amt37urbhqgpuuv4ve.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/google

          kakao:
            client-id: 6b1d134980644fe3a21d1a0f09b52c4d
            client-secret: 6CE5ZNnGwrIfqkAjBENpiFIik67OsSdE
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: hbhB10Tk7nEfIWzdZDnW
            client-secret: TR7P0nBX0D
            scope:
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://yoonsever.xn--h32bi4v.xn--3e0b707e:443/login/oauth2/code/naver

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://yoondb.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/yoondb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 실제 엔드포인트와 DB 이름
    username: admin   # 실제 사용자 이름
    password: uionrtqwe   # 실제 사용자 비번
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 처음에는 create -> 나중에는 update
    show-sql: true
  spring:
    servlet:
      multipart:
        enabled: true # multipart 기능 활성화
        max-file-size: 10MB # 업로드할 파일의 최대 크기
        max-request-size: 10MB # 요청 크기 제한
        file-size-threshold: 2KB # 임시 파일이 저장될 크기

cloud:
  aws:
    s3:
      bucket: yoons-s3  # 실제 s3 버킷 이름
    region:
      static: ap-northeast-2 # 실제 지역
    stack:
      auto: false
    credentials:
      accessKey: AKIAU6VTTQ4ELQ5SZGN7 # 실제 엑세스 키
      secretKey: OMKKodLRRbtRydixVYioqswC/DMHE/NH+oEwyGFs
